image: maven:3-jdk-11

clone:
  depth: full

definitions:
  caches:
    node-cache: browser/node_modules


pipelines:
# Pipelines that run automatically on a commit to a branch
  branches:
    IMP-*:
      - step:
          caches:
            - node-cache
            - maven
          size: 2x
          script:
            - mvn clean test -P qa -B -Dmaven.wagon.http.pool=false

    master:
      - step:
          caches:
            - maven
            - node-cache
          size: 2x
          script:
            # Should run integration tests in FUTURE
            - mvn clean test -P qa -B -Dmaven.wagon.http.pool=false


# Pipelines that are triggered manually
  custom:
    push-to-heroku-prod:
      - step:
          name: Deploy master to heroku PROD
          caches:
             - maven
             - node-cache
          script:
             - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD

    push-branch-to-heroku-prod:
      - step:
          name: Deploy branch to heroku
          caches:
             - maven
             - node-cache
          script:
            # - git pull https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
             - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
