package com.improver.util.database.test;

import com.improver.entity.Question;
import com.improver.entity.Questionary;

import static com.improver.application.properties.Path.PATH_IMGS_SERVICE_TILING;

public class QuestionaryInitializer {

    public static Questionary architecturalServices(Questionary questionary) {
        return questionary
            .setName("architecturalServices")
            .setDescription("Questionary for Attic Remodel")
            .addQuestion(new Question()
                .setTitle("Test input question")
                .setLabel("Test input question")
                .setType(Question.Type.TEXT_INPUT))
            .addQuestion(new Question()
                .setTitle("Test textarea question")
                .setLabel("Test textarea question")
                .setType(Question.Type.TEXT_AREA))
            .addQuestion(new Question()
                .setTitle("Test numeric input question")
                .setLabel("Test numeric input question")
                .setType(Question.Type.NUMERIC_INPUT))
            .addQuestion(new Question()
                .setTitle("Test radio button?")
                .setType(Question.Type.RADIO_BUTTON)
                .addAnswer("Answer 1")
                .addAnswer("Answer 2")
                .addAnswer("Answer 3")
                .addAnswer("Answer 4"))
            .addQuestion(new Question()
                .setTitle("Test img radio button?")
                .setType(Question.Type.IMG_RADIO_BUTTON)
                .addAnswer("Answer 1")
                .addAnswer("Answer 2")
                .addAnswer("Answer 3")
                .addAnswer("Answer 4"))
            .addQuestion(new Question()
                .setTitle("Test checkbox button?")
                .setType(Question.Type.CHECK_BOX)
                .addAnswer("Answer 1")
                .addAnswer("Answer 2")
                .addAnswer("Answer 3")
                .addAnswer("Answer 4"))
            .addQuestion(new Question()
                .setTitle("Test img checkbox button?")
                .setType(Question.Type.IMG_CHECK_BOX)
                .addAnswer("Answer 1")
                .addAnswer("Answer 2")
                .addAnswer("Answer 3")
                .addAnswer("Answer 4"));
    }


    @Deprecated
    public static Questionary defaultQuestionary(Questionary questionary) {
        return questionary
            .setName("defaultQuestionary")
            .setDescription("Default set of questions")
            .addQuestion(new Question()
                .setName("project_estimate_expectations")
                .setTitle("When do you need your project started?")
                .setType(Question.Type.RADIO_BUTTON)
                .addAnswer("I'm flexible")
                .addAnswer("Within 48 hours")
                .addAnswer("Within a week")
                .addAnswer("Within a month")
                .addAnswer("Within a year"))
            .addQuestion(new Question()
                .setName("type_of_property")
                .setTitle("What type of property do you have?")
                .setType(Question.Type.CHECK_BOX)
                .addAnswer("Home")
                .addAnswer("Multi-unit building")
                .addAnswer("Office / business")
                .addAnswer("Commercial")
                .addAnswer("Other"))
            .addQuestion(new Question()
                .setName("additional_information_about_project")
                .setLabel("Project details")
                .setTitle("Please provide some project details for Professional")
                .setType(Question.Type.TEXT_AREA))
            .addQuestion(new Question()
                .setName("customer_full_name")
                .setLabel("Full name")
                .setTitle("Let's getDetailedForPro acquainted?")
                .setType(Question.Type.TEXT_INPUT))
            .addQuestion(new Question()
                .setName("customer_contacts")
                .setLabel("Email")
                .setTitle("What's the best way to getDetailedForPro in contact?")
                .setType(Question.Type.TEXT_INPUT))
            .addQuestion(new Question()
                .setName("project_location")
                .setLabel("Zip code")
                .setTitle("Where do you need a Professional?")
                .setType(Question.Type.TEXT_INPUT));
    }

    public static Questionary kitchenTilingQuestionary(Questionary questionary) {
        return questionary
            .setName("kitchenTilingQuestionary")
            .setDescription("Questionary for Kitchen Tiling")
            .addQuestion(new Question()
                .setTitle("What kind of work?")
                .setType(Question.Type.RADIO_BUTTON)
                .addAnswer("Install")
                .addAnswer("Replace"))
            .addQuestion(new Question()
                .setTitle("What kind of tile are you interested in?")
                .setType(Question.Type.IMG_RADIO_BUTTON)
                .addAnswer("Ceramic", PATH_IMGS_SERVICE_TILING + "1_ceramic_tile.png")
                .addAnswer("Encaustic", PATH_IMGS_SERVICE_TILING + "2_encaustic_tile.png")
                .addAnswer("Glass", PATH_IMGS_SERVICE_TILING + "3_glass_tile.jpg")
                .addAnswer("Granite", PATH_IMGS_SERVICE_TILING + "4_granite_tile.jpg")
                .addAnswer("Porcelain", PATH_IMGS_SERVICE_TILING + "5_porcelain_tile.jpg")
                .addAnswer("Saltillo", PATH_IMGS_SERVICE_TILING + "6_saltillo_tile.jpg")
                .addAnswer("Slate", PATH_IMGS_SERVICE_TILING + "7_slate_tile.jpg")
                .addAnswer("Terracotta", PATH_IMGS_SERVICE_TILING + "8_terracotta_tile.jpg")
                .addAnswer("Terrazzo", PATH_IMGS_SERVICE_TILING + "9_terrazzo_tile.jpg"))
            .addQuestion(new Question()
                .setTitle("What quality/price level tile you want to buy?")
                .setType(Question.Type.RADIO_BUTTON)
                .addAnswer("Low")
                .addAnswer("Middle")
                .addAnswer("High"))
            .addQuestion(new Question()
                .setTitle("What would you like tiled?")
                .setType(Question.Type.CHECK_BOX)
                .addAnswer("Countertop")
                .addAnswer("Wall")
                .addAnswer("Floor")
                .addAnswer("Backsplash")
                .addAnswer("Island"))
            .addQuestion(new Question()
                .setTitle("Approximately how many square feet is the area that needs tiling?")
                .setType(Question.Type.NUMERIC_INPUT)
                .setLabel("Approximate square footage of area to tile (sq ft)"))
            .addQuestion(new Question()
                .setTitle("Does the area to be tiled need to be stripped of any existing surface material?")
                .setType(Question.Type.RADIO_BUTTON)
                .addAnswer("Yes, existing tile needs to be removed")
                .addAnswer("Yes, carpet or other non-tile material needs to be removed")
                .addAnswer("No existing material (e.g., tile, carpet) needs to be removed"))
            .addQuestion(new Question()
                .setTitle("What material will the tile be installed over?")
                .setType(Question.Type.RADIO_BUTTON)
                .addAnswer("Concrete")
                .addAnswer("Wood")
                .addAnswer("Drywall")
                .addAnswer("Other"));
    }
}
