---
services:
  database:
    image: postgres:14
    container_name: postgres
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_DB: improve
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 15s
      timeout: 3s
      interval: 10s
      retries: 12
